version: '3.8'
services:
  mysql:
    container_name: education-app-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'education_app'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'