version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "education_app"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"