name: Build image

permissions:
  packages: write

on:
  workflow_run:
    workflows: [ "Main" ]
    branches: [ master ]
    types:
      - completed

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Package with Maven
        run: mvn package -DskipTests --no-transfer-progress
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          dockerfile: ./image/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: uwithme-service
          image-tag: latest
          custom-args: --platform=linux/arm64,linux/amd64