name: Main

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: build-archive
    steps:
      - name: Set up JRE 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          java-package: jre
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Download docker containers
        uses: actions/checkout@v3
        with:
          repository: HappyMary16/uwithme-docker-files
          path: ./uwithme-docker-files
      - name: Run docker-compose
        working-directory: ./uwithme-docker-files
        run: docker compose up -d

      - name: Download tests
        uses: actions/checkout@v3
        with:
          path: ./uwithme-repo
      - name: Package with Mavwn
        working-directory: ./uwithme-repo
        run: mvn package -DskipTests
      - name: Start the service
        working-directory: ./uwithme-repo
        run: java -jar /uwithme-service/target//UwithmeServiceApp.jar &
      - name: Wait for the service
        timeout-minutes: 1
        run: while ! echo exit | nc localhost 8081; do sleep 10; done

      - name: Run tests
        working-directory: ./uwithme-repo
        timeout-minutes: 5
        run: mvn -pl uwithme-func-tests test