name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Set up Docker
        uses: withlogicco/setup-compose-cli@v1

      - name: Download docker containers
        uses: actions/checkout@v3
        with:
          repository: HappyMary16/uwithme-docker-files
          path: ./uwithme-docker-files
      - name: Run docker-compose
        working-directory: ./uwithme-docker-files
        run: docker compose up -d

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./uwithme-repo
      - name: Package with Maven
        working-directory: ./uwithme-repo
        run: mvn install -DskipTests --no-transfer-progress
      - name: Start the service
        working-directory: ./uwithme-repo
        run: java -jar ./uwithme-service/target/UwithmeServiceApp.jar &
      - name: Wait for the service
        timeout-minutes: 1
        run: while ! echo exit | nc localhost 8081; do sleep 10; done

      - name: Run tests
        working-directory: ./uwithme-repo
        timeout-minutes: 5
        run: mvn -pl uwithme-func-tests test --no-transfer-progress