name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    needs: build-archive
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: EducationApp
          path: ./university-with-me-service/target/EducationApp.jar
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Grant execute permission for deploy script
        run: chmod +x ./deploy.sh
      - name: Deploy
        run: ./deploy.sh